TGClothes/Models/ProductStatistic.cs
using Data.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TGClothes.Models
{
    public class ProductStatistic
    {
        public Product Product { get; set; }
        public int ProductSold { get; set; }
        public decimal Price { get; set; }
    }
}

TGClothes/Areas/Admin/Controllers/RevenueStatisticController.cs
using Data.Services;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using TGClothes.Models;
using OfficeOpenXml;
using System.IO;
using System.ComponentModel;

namespace TGClothes.Areas.Admin.Controllers
{
    public class RevenueStatisticController : BaseController
    {
        private readonly IOrderDetailService _orderDetailService;
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;

        public RevenueStatisticController(IOrderDetailService orderDetailService, IOrderService orderService, IProductService productService)
        {
            _orderDetailService = orderDetailService;
            _orderService = orderService;
            _productService = productService;
        }
        // GET: Admin/RevenueStatistic
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrderStatistic(DateTime? fromDate, DateTime? toDate)
        {
            if (!fromDate.HasValue && !toDate.HasValue)
            {

                var data = (from o in _orderService.GetAll()
                            join od in _orderDetailService.GetAll() on o.Id equals od.OrderId
                            where o.OrderDate.Month == DateTime.Now.Month && o.Status == (int)OrderStatus.SUCCESSFUL
                            group o by o.OrderDate.Date into g
                            select new
                            {
                                Date = g.Key,
                                TotalOrdersSold = g.Count()
                            }).ToList();

                ViewBag.TotalOrder = data.Sum(x => x.TotalOrdersSold);
                ViewBag.NumOfOrder = data.Select(x => x.TotalOrdersSold);
                ViewBag.DateOrder = data.Select(x => x.Date.ToString("yyyy-MM-dd")).ToList();
                return View(data);
            }
            else
            {
                var data = (from o in _orderService.GetAll()
                            join od in _orderDetailService.GetAll() on o.Id equals od.OrderId
                            where o.OrderDate >= fromDate && o.OrderDate <= toDate && o.Status == (int)OrderStatus.SUCCESSFUL
                            group o by o.OrderDate.Date into g
                            select new
                            {
                                Date = g.Key,
                                TotalOrdersSold = g.Count()
                            }).ToList();

                ViewBag.TotalOrder = data.Sum(x => x.TotalOrdersSold);
                ViewBag.NumOfOrder = data.Select(x => x.TotalOrdersSold);
                ViewBag.DateOrder = data.Select(x => x.Date.ToString("yyyy-MM-dd")).ToList();
                return View(data);
            }
        }

        [HttpPost]
        public ActionResult ExportToExcel(string fromDate, string toDate)
        {
            DateTime? startDate = null;
            DateTime? endDate = null;

            // Chuyển đổi tham số từ string sang DateTime
            if (!string.IsNullOrEmpty(fromDate))
                startDate = DateTime.Parse(fromDate);
            if (!string.IsNullOrEmpty(toDate))
                endDate = DateTime.Parse(toDate);

            // Truy vấn dữ liệu
            var data = (from o in _orderService.GetAll()
                        join od in _orderDetailService.GetAll() on o.Id equals od.OrderId
                        join p in _productService.GetAll() on od.ProductId equals p.Id
                        where (!startDate.HasValue || o.OrderDate >= startDate)
                              && (!endDate.HasValue || o.OrderDate <= endDate)
                              && o.Status == (int)OrderStatus.SUCCESSFUL
                        group new { od, p } by o.OrderDate.Date into g
                        select new
                        {
                            Date = g.Key,
                            Revenue = g.Sum(x => x.od.Price * x.od.Quantity),
                            Profit = g.Sum(x => (x.od.Price - x.p.OriginalPrice) * x.od.Quantity)
                        }).ToList();

            // Tạo file Excel
            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Revenue Statistics");
                worksheet.Cells[1, 1].Value = "Ngày";
                worksheet.Cells[1, 2].Value = "Doanh thu";
                worksheet.Cells[1, 3].Value = "Lợi nhuận";

                int row = 2;
                foreach (var item in data)
                {
                    worksheet.Cells[row, 1].Value = item.Date.ToString("yyyy-MM-dd");
                    worksheet.Cells[row, 2].Value = item.Revenue;
                    worksheet.Cells[row, 3].Value = item.Profit;
                    row++;
                }

                worksheet.Cells[1, 1, row - 1, 3].AutoFitColumns();
                worksheet.Cells[1, 1, 1, 3].Style.Font.Bold = true;

                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Position = 0;
                string excelName = $"Thống Kê Doanh Thu {DateTime.Now.ToString("yyyyMMdd")}.xlsx";

                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
            }
        }


        public ActionResult RevenueStatistic(DateTime? fromDate, DateTime? toDate)
        {
            if (!fromDate.HasValue && !toDate.HasValue)
            {

                var data = (from o in _orderService.GetAll()
                            join od in _orderDetailService.GetAll() on o.Id equals od.OrderId
                            join p in _productService.GetAll() on od.ProductId equals p.Id
                            where o.OrderDate.Month == DateTime.Now.Month 
                          && o.OrderDate.Year == DateTime.Now.Year
                          && o.Status == (int)OrderStatus.SUCCESSFUL
                            group new { od, p } by o.OrderDate.Date into g
                            select new
                            {
                                Date = g.Key,
                                Revenue = g.Sum(x => x.od.Price * x.od.Quantity),
                                Profit = g.Sum(x => (x.od.Price - x.p.OriginalPrice) * x.od.Quantity)
                            }).ToList();

                ViewBag.TotalRevenue = data.Sum(x => x.Revenue);
                ViewBag.TotalProfit = data.Sum(x => x.Profit);
                ViewBag.RevenueOfDay = data.Select(x => x.Revenue);
                ViewBag.ProfitOfDay = data.Select(x => x.Profit);
                ViewBag.DateOrder = data.Select(x => x.Date.ToString("yyyy-MM-dd")).ToList();
                return View(data);
            }
            else
            {
                var data = (from o in _orderService.GetAll()
                            join od in _orderDetailService.GetAll() on o.Id equals od.OrderId
                            join p in _productService.GetAll() on od.ProductId equals p.Id
                            where o.OrderDate >= fromDate && o.OrderDate <= toDate && o.Status == (int)OrderStatus.SUCCESSFUL
                            group new { od, p } by o.OrderDate.Date into g
                            select new
                            {
                                Date = g.Key,
                                Revenue = g.Sum(x => x.od.Price * x.od.Quantity),
                                Profit = g.Sum(x => (x.od.Price - x.p.OriginalPrice) * x.od.Quantity)
                            }).ToList();

                ViewBag.TotalRevenue = data.Sum(x => x.Revenue);
                ViewBag.TotalProfit = data.Sum(x => x.Profit);
                ViewBag.RevenueOfDay = data.Select(x => x.Revenue);
                ViewBag.ProfitOfDay = data.Select(x => x.Profit);
                ViewBag.DateOrder = data.Select(x => x.Date.ToString("yyyy-MM-dd")).ToList();
                return View(data);
            }
        }

        public ActionResult ProductStatistic(DateTime? fromDate, DateTime? toDate, string filterType, int page = 1, int pageSize = 10)
        {
            // Dữ liệu mặc định nếu không có filterType
            var productsQuery = _orderService.GetAll()
                .Join(_orderDetailService.GetAll(), o => o.Id, od => od.OrderId, (o, od) => new { o, od })
                .Join(_productService.GetAll(), x => x.od.ProductId, p => p.Id, (x, p) => new { x.o, x.od, p })
                .Where(x => x.o.Status == (int)OrderStatus.SUCCESSFUL);

            // Nếu có chọn ngày
            if (fromDate.HasValue && toDate.HasValue)
            {
                productsQuery = productsQuery.Where(x => x.o.OrderDate >= fromDate && x.o.OrderDate <= toDate);
            }

            // Lọc dữ liệu theo filterType
            IEnumerable<ProductStatistic> result = new List<ProductStatistic>();

            switch (filterType)
            {
                case "Top5":
                    result = (from x in productsQuery
                              group x by x.od.ProductId into g
                              select new ProductStatistic()
                              {
                                  ProductSold = g.Sum(x => x.od.Quantity),
                                  Product = _productService.GetProductById(g.Key),
                                  Price = g.First().od.Price.Value
                              }).OrderByDescending(x => x.ProductSold).Take(5);
                    break;

                case "Bottom5":
                    result = (from x in productsQuery
                              group x by x.od.ProductId into g
                              select new ProductStatistic()
                              {
                                  ProductSold = g.Sum(x => x.od.Quantity),
                                  Product = _productService.GetProductById(g.Key),

TGClothes/Areas/Admin/Views/RevenueStatistic/Index.cshtml
@model IEnumerable<Data.EF.Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header {
    Thống kê    
}

    <div class="col-lg-12 padding-8">


        @using (Html.BeginForm("RevenueByDay", "RevenueStatistic", FormMethod.Post))
        {
            <h4 class="text-danger">@Html.Raw(TempData["msgDate"])</h4>
            <h3 class="mt-5">Doanh thu theo ngày</h3>
            <input type="date" name="date" required />

            <input type="submit" value="Kiểm tra" />

        }

        @using (Html.BeginForm("DoanhThuThang", "Admin", FormMethod.Post))
        {
            <h3 class="mt-5">Doanh thu theo tháng</h3>
            <input type="date" name="NgayGiao" required />

            <input type="submit" value="Kiểm tra" />

        }

        @using (Html.BeginForm("DoanhThuNam", "Admin", FormMethod.Post))
        {
            <h3 class="mt-5">Doanh thu theo năm</h3>
            <input type="date" name="NgayGiao" required />

            <input type="submit" value="Kiểm tra" />

        }


    </div>

TGClothes/Areas/Admin/Views/RevenueStatistic/OrderStatistic.cshtml
@{
    ViewBag.Title = "OrderStatistic";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header {
    Thống kê đơn hàng    
}

<div class="row">
    <div class="col-xl-12 col-lg-12 mb-3">
        @using (Html.BeginForm("OrderStatistic", "RevenueStatistic", FormMethod.Get))
        {
            <div class="row form-group">
                <div class="col-lg-12 row">
                    <div class="col-md-12">
                        <span>Từ ngày</span>
                        <input type="date" name="fromDate" required class="mr-2" id="fromDate"/>
                        <span>Đến ngày</span>
                        <input type="date" name="toDate" required class="mr-2" id="toDate"/>
                        <button type="submit" class="btn btn-outline-success">Tìm kiếm</button>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-info">Số lượng đơn hàng theo mốc</h6>
                <h6 class="m-0 font-weight-bold text-primary">Tổng đơn: @ViewBag.TotalOrder</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
@section CustomJs{
    <!-- Page level plugins -->
    <script src="/Assets/Admin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/Assets/Admin/js/demo/chart-area-demo.js"></script>

    <script>
        var ctx = document.getElementById("myAreaChart");

        var numOfOrder =  @Html.Raw(Json.Encode(ViewBag.NumOfOrder));
        var dateOrder =  @Html.Raw(Json.Encode(ViewBag.DateOrder));

        var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: dateOrder,
                datasets: [{
                    label: "Tổng đơn hàng",
                    lineTension: 0.3,
                    backgroundColor: "rgba(78, 115, 223, 0.05)",
                    borderColor: "rgba(78, 115, 223, 1)",
                    pointRadius: 3,
                    pointBackgroundColor: "rgba(78, 115, 223, 1)",
                    pointBorderColor: "rgba(78, 115, 223, 1)",
                    pointHoverRadius: 3,
                    pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
                    pointHoverBorderColor: "rgba(78, 115, 223, 1)",
                    pointHitRadius: 10,
                    pointBorderWidth: 2,
                    data: numOfOrder,
                }],
            },
            options: {
                maintainAspectRatio: false,
                layout: {
                    padding: {
                        left: 10,
                        right: 25,
                        top: 25,
                        bottom: 0
                    }
                },
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'date'
                        },
                        gridLines: {
                            display: false,
                            drawBorder: false
                        },
                        ticks: {
                            maxTicksLimit: 10,
                            callback: function (value) {
                                return value.substr(0, 10)+"...";
                            },
                        }
                    }],
                    yAxes: [{
                        ticks: {
                            maxTicksLimit: 5,
                            padding: 10,
                            // Include a dollar sign in the ticks
                            callback: function (value, index, values) {
                                return number_format(value);
                            }
                        },
                        gridLines: {
                            color: "rgb(234, 236, 244)",
                            zeroLineColor: "rgb(234, 236, 244)",
                            drawBorder: false,
                            borderDash: [2],
                            zeroLineBorderDash: [2]
                        }
                    }],
                },
                legend: {
                    display: false
                },
                tooltips: {
                    backgroundColor: "rgb(255,255,255)",
                    bodyFontColor: "#858796",
                    titleMarginBottom: 10,
                    titleFontColor: '#6e707e',
                    titleFontSize: 14,
                    borderColor: '#dddfeb',
                    borderWidth: 1,
                    xPadding: 15,
                    yPadding: 15,
                    displayColors: false,
                    intersect: false,
                    mode: 'index',
                    caretPadding: 10,
                    callbacks: {
                        label: function (tooltipItem, chart) {
                            var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
                            return datasetLabel + ': ' + number_format(tooltipItem.yLabel);
                        }
                    }
                }
            }
        });
    </script>
}

TGClothes/Areas/Admin/Views/RevenueStatistic/ProductStatistic.cshtml
@model PagedList.IPagedList<TGClothes.Models.ProductStatistic>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ProductStatistic";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var filterType = ViewBag.FilterType ?? "All"; // Mặc định là All
}

@section header {
    Thống kê sản phẩm bán ra
}

<div class="card shadow mb-4">
    <div class="card-body">
        @using (Html.BeginForm("ProductStatistic", "RevenueStatistic", FormMethod.Get))
        {
            <div class="row form-group">
                <div class="col-lg-12 row">
                    <div class="col-md-7">
                        <span>Từ ngày</span>
                        <input type="date" name="fromDate" id="fromDate" value="@ViewBag.FromDate" class="mr-2" />
                        <span>Đến ngày</span>
                        <input type="date" name="toDate" id="toDate" value="@ViewBag.ToDate" class="mr-2" />
                        <button type="submit" class="btn btn-outline-success mr-2">Tìm kiếm</button>
                        <a href="/Admin/RevenueStatistic/ProductStatistic" class="btn btn-outline-success">Refresh</a>
                    </div>
                    <div class="col-md-4">
                        <h4 class="text-danger mt-3">Tổng số sản phẩm bán ra: @ViewBag.TotalProductSold</h4>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="filterType" class="font-weight-bold">Chọn lọc sản phẩm:</label>
                <select name="filterType" id="filterType" class="form-control custom-select" onchange="this.form.submit()">
                    <option value="All" @(filterType == "All" ? "selected" : "")>Tất cả sản phẩm</option>
                    <option value="Top5" @(filterType == "Top5" ? "selected" : "")>Top 5 bán chạy</option>
                    <option value="Bottom5" @(filterType == "Bottom5" ? "selected" : "")>Top 5 bán ế</option>
                </select>
            </div>

       
        }

        <!-- Table displaying product statistics -->
        <div class="table-responsive" style="overflow-x: hidden;">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr class="text-center">
                                    <th class="text-left">Tên sản phẩm</th>
                                    <th>Hình ảnh</th>
                                    <th>Số lượng bán</th>
                                    <th>Giá bán</th>
                                    <th>Thành tiền</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="text-center">
                                        <td class="text-left">@item.Product.Name</td>
                                        <td><img src="@item.Product.Image" height="100px" /></td>
                                        <td>@item.ProductSold</td>
                                        <td>@item.Price.ToString("N0")</td>
                                        <td>@((item.ProductSold * item.Price).ToString("N0"))</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pagination -->
        <div class="text-center">
            @Html.PagedListPager(Model, page => Url.Action("ProductStatistic", "RevenueStatistic", new { filterType = filterType, page }), PagedListRenderOptions.Classic)
        </div>
    </div>
</div>
<style>
    /* Cải thiện giao diện combobox */
    select.form-control.custom-select {
        border-radius: 0.375rem; /* Bo góc mềm mại */
        padding: 0.5rem 1rem; /* Thêm khoảng cách bên trong */
        font-size: 1rem; /* Kích thước chữ vừa phải */
        color: #495057; /* Màu chữ tối để dễ đọc */
        background-color: #ffffff; /* Màu nền trắng */
        background-image: none; /* Loại bỏ mũi tên mặc định */
        border: 1px solid #ced4da; /* Viền mờ, sạch sẽ */
        appearance: none; /* Loại bỏ kiểu dáng mặc định của các trình duyệt */
        transition: all 0.3s ease; /* Thêm hiệu ứng chuyển động khi focus */
    }

        select.form-control.custom-select:focus {
            border-color: #80bdff; /* Viền màu xanh khi focus */
            background-color: #f1faff; /* Nền sáng khi focus */
            outline: none; /* Loại bỏ outline mặc định */
        }

        /* Thêm hiệu ứng hover khi di chuột qua combobox */
        select.form-control.custom-select:hover {
            border-color: #5c9cfa; /* Viền chuyển màu khi hover */
            background-color: #e9f3ff; /* Nền chuyển màu khi hover */
        }

        /* Tạo hiệu ứng khi người dùng chọn combobox */
        select.form-control.custom-select:disabled {
            background-color: #f1f1f1; /* Màu nền khi combobox bị vô hiệu hóa */
            color: #a0a0a0; /* Màu chữ khi bị vô hiệu hóa */
        }

        /* Ẩn mũi tên của combobox trong IE */
        select.form-control.custom-select::-ms-expand {
            display: none;
        }

        /* Thêm mũi tên đẹp hơn cho combobox trên các trình duyệt khác */
        select.form-control.custom-select:after {
            content: '\f0d7'; /* Mã unicode cho mũi tên */
            font-family: FontAwesome; /* Dùng font FontAwesome */
            position: absolute;
            right: 1rem;
            top: 50%;
            transform: translateY(-50%);
        }

    select.form-control {
        border-radius: 0.375rem;
        padding: 0.5rem 1rem;
        font-size: 1rem;
        color: #495057;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ced4da;
        appearance: none;
    }

        select.form-control:focus {
            border-color: #80bdff;
            outline: none;
        }

</style>

TGClothes/Areas/Admin/Views/RevenueStatistic/RevenueByDay.cshtml
@model IEnumerable<Data.EF.Order>
@{
    ViewBag.Title = "RevenueByDay";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header {
    Doanh thu ngày
}

<div class="col-lg-12 padding-8 ViewPrint">
    @*<h3>Doanh thu theo Ngày @ViewBag.Ngay<span> Tháng @ViewBag.Thang</span> <span> Năm @ViewBag.Nam</span></h3>*@

    <h3>Tổng số lượng sản phẩm bán được trong ngày: @ViewBag.CountOfOrder</h3>

    @*<h2>Tổng doanh thu trong ngày: @String.Format("{0:N0}", @ViewBag.DoanhThuNgay) vnđ</h2>*@

    <div class="body fix-width scroll-inner">
        <table class="table table-striped">
            <tr>
                <th>Tên khách hàng</th>
                <th>Phương thức thanh toán</th>
                <th>Ngày đặt</th>
                <th>Ngày giao</th>
                <th>Thao tác</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.PaymentMethod</td>
                    <td>@item.OrderDate</td>
                    <td>@item.DeliveryDate</td>
                    <td>
                        <a href="@Url.Action("Details", "Order", new { id = @item.Id })">Chi tiết đơn hàng</a>
                    </td>
                </tr>

            }
        </table>
    </div>
    @if (ViewBag.ToTalPage > 1)
    {
        var pageDisplay = (int)ViewBag.MaxPage;
        var totalPage = (int)ViewBag.TotalPage;
        var currentPage = (int)ViewBag.Page;

        //Create numeric link
        var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
        var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);

        var link = "/RevenueStatistic/RevenueByDay?date=" + ViewBag.Date;
<nav class="d-flex justify-content-center">
    <ul class="pagination">
        @if (currentPage > ViewBag.First)
        {
<li class="page-item"><a href="@link&page=@ViewBag.First" title="Trang đầu" class="first flex-c-m how-pagination1 trans-04 m-all-7"><i class="fa fa-angle-double-left"></i></a></li>
                    <li class="page-item">
                        <a href="@link&page=@ViewBag.Prev" title="Trang trước" class="prev flex-c-m how-pagination1 trans-04 m-all-7"><i class="fa fa-angle-left"></i></a>
                    </li>}
        @for (int i = startPageIndex; i <= endPageIndex; i++)
        {
            if (currentPage == i)
            {

<li class="page-item active"> <a href="@link&page=@i" class="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1" title="Trang @i">@i</a></li> }
                    else
                    {
<li class="page-item"><a href="@link&page=@i" title="Trang @i" class="pos flex-c-m how-pagination1 trans-04 m-all-7">@i</a></li>}
                }
        @if (currentPage < totalPage)
        {
<li class="page-item"><a href="@link&page=@ViewBag.Next" class="next flex-c-m how-pagination1 trans-04 m-all-7" title="Trang sau"><i class="fa fa-angle-right"></i></a></li>
                    <li class="page-item"> <a href="@link&page=@ViewBag.Last" class="last flex-c-m how-pagination1 trans-04 m-all-7" title="Trang cuối"><i class="fa fa-angle-double-right"></i></a></li>}

    </ul>
</nav> }
            else if (ViewBag.ToTalPage == 1)
            {
<span></span> }
            else
            {
<span>Không có bản ghi nào</span>}
</div>

<div class="body padding-8" style="border: none; box-shadow: none; border-radius: none; margin-top: 10px;">
    <div>
        <button id="Print" class="btn btn-primary">Print</button>
    </div>

    <div class="mt-2">
        @Html.ActionLink("Quay lại", "Index")
    </div>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="~/Content/admin/js/printThis.js"></script>


<script>
    jQuery(document).ready(function ($) {
        $('#Print').on("click", function () {
            $('.ViewPrint').printThis({
                debug: false,               // show the iframe for debugging
                importCSS: true,            // import parent page css
                importStyle: false,         // import style tags
                printContainer: true,       // print outer container/$.selector
                loadCSS: "",                // path to additional css file - use an array [] for multiple
                pageTitle: "",              // add title to print page
                removeInline: false,        // remove inline styles from print elements
                removeInlineSelector: "*",  // custom selectors to filter inline styles. removeInline must be true
                printDelay: 333,            // variable print delay
                header: null,               // prefix to html
                footer: null,               // postfix to html
                base: false,                // preserve the BASE tag or accept a string for the URL
                formValues: true,           // preserve input/form values
                canvas: false,              // copy canvas content
                doctypeString: '...',       // enter a different doctype for older markup
                removeScripts: false,       // remove script tags from print content
                copyTagClasses: false,      // copy classes from the html & body tag
                beforePrintEvent: null,     // function for printEvent in iframe
                beforePrint: null,          // function called before iframe is filled
                afterPrint: null            // function called before iframe is removed
            });
        });
    });
</script>

TGClothes/Areas/Admin/Views/RevenueStatistic/_ProductStatisticTable.cshtml
@model IEnumerable<TGClothes.Models.ProductStatistic>

<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <tr class="text-center">
            <th class="text-left">Tên sản phẩm</th>
            <th>Hình ảnh</th>
            <th>Số lượng bán</th>
            <th>Giá bán</th>
            <th>Thành tiền</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-center">
                <td class="text-left">@item.Product.Name</td>
                <td><img src="@item.Product.Image" height="100px" /></td>
                <td>@item.ProductSold</td>
                <td>@item.Price.ToString("N0")</td>
                <td>@((item.ProductSold * item.Price).ToString("N0"))</td>
            </tr>
        }
    </tbody>
</table>