TGClothes/Areas/Admin/Controllers/FeedbackController.cs
using Data.Services;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TGClothes.Areas.Admin.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IFeedbackService _feedbackService;

        public FeedbackController(IFeedbackService feedbackService)
        {
            _feedbackService = feedbackService;
        }

        // GET: Admin/Feedback
        public ActionResult Index(int page = 1, int pageSize = 5)
        {
            var feedbacks = _feedbackService.GetAll()
                                            .OrderByDescending(x => x.CreatedDate)
                                            .ToList();

            int totalRecords = feedbacks.Count();
            var pagedFeedbacks = feedbacks.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.TotalPages = (int)Math.Ceiling((double)totalRecords / pageSize);
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = pageSize;

            return View(pagedFeedbacks);
        }



        [HttpDelete]
        public ActionResult Delete(long id)
        {
            _feedbackService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

TGClothes/Areas/Admin/Views/Feedback/Index.cshtml
@model IEnumerable<Data.EF.Feedback>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header {
    Quản lý Feedback
}

<div class="table-responsive" style="overflow-x: hidden;">
    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="text-center">
                            <th class="text-left">Tên khách hàng</th>
                            <th>Email</th>
                            <th>Số điện thoại</th>
                            <th>Địa chỉ</th>
                            <th>Nội dung</th>
                            <th>Ngày tạo</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr id="row_@item.Id" class="text-center">
                                <td style="word-wrap: break-word; max-width: 240px;" class="text-left">@item.Name</td>
                                <td>@item.Email</td>
                                <td>@item.Phone</td>
                                <td>@item.Address</td>
                                <td>@item.Content</td>
                                <td>@item.CreatedDate</td>
                                <td>
                                    <a href="@Url.Action("Delete", "Feedback", new { id = item.Id })"
                                       class="btn text-primary f1"
                                       data-ajax="true"
                                       data-ajax-method="delete"
                                       data-ajax-confirm="Bạn có muốn xóa bản ghi này?"
                                       data-ajax-complete="false">
                                        <i class='fa-solid fa-trash-can'></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="pagination-container text-center">
                    <nav>
                        <ul class="pagination justify-content-center">
                            @if (ViewBag.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage - 1, pageSize = ViewBag.PageSize })">&laquo;</a>
                                </li>
                            }

                            @for (int i = 1; i <= ViewBag.TotalPages; i++)
                            {
                                if (i == ViewBag.CurrentPage)
                                {
                                    <li class="page-item active">
                                        <span class="page-link">@i</span>
                                    </li>
                                }
                                else
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = i, pageSize = ViewBag.PageSize })">@i</a>
                                    </li>
                                }
                            }

                            @if (ViewBag.CurrentPage < ViewBag.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage + 1, pageSize = ViewBag.PageSize })">&raquo;</a>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>